"""Master catalog of every translatable UI string in the application."""

# Navigation, chrome, and shared labels
COMMON_STRINGS = [
    "BizAssist AI",
    "Smart Business",
    "AI Active",
    "Dashboard",
    "Inventory",
    "Orders",
    "Marketing",
    "Finance",
    "Customers",
    "AI Assistant",
    "Business Profile",
    "Local offers",
    "My account",
    "AI Powered",
    "Your intelligent business companion for growth and efficiency.",
    "AI Active",
    "Settings",
    "Log out",
    "Language:",
    "AI Mic",
    "Account",
    "This field is required.",
    "UI",
    "Replies",
    "Revenue",
    "Net Profit",
    "VIP Customers",
    "Quick AI mic",
]

LANGUAGE_SELECT_STRINGS = [
    "Select Language - BizAssist AI",
    "Select your language",
    "Choose the language you want BizAssist AI to use across the whole app. After selection, the interface and AI assistant will speak in your language.",
    "Choose the language you want BizAssist AI to use across the whole app. After selection, every page opens already translated.",
    "You can switch language anytime using the blue floating button in the app.",
]

LOGIN_STRINGS = [
    "Business Profile - BizAssist AI",
    "Business Login - BizAssist AI",
    "Business Profile",
    "Business Onboarding / Login",
    "Enter shop/business and financial details. Net profit and all graphs will calculate from this data.",
    "Please enter your shop or business location.",
    "Personal & Business Details",
    "Owner Full Name",
    "Shop / Business Name",
    "Email",
    "Phone",
    "Shop / business location (city / area — used for local offers)",
    "e.g. MG Road, Bengaluru",
    "Shop / Business Type",
    "Retail",
    "E-commerce",
    "Service",
    "Restaurant",
    "Manufacturing",
    "Other",
    "Campaign sender Gmail",
    "yourname@gmail.com (optional)",
    "Campaign sender App Password",
    "16-character Gmail App Password (optional)",
    "Marketing / Financial Status",
    "Current Monthly Revenue (₹)",
    "Current Monthly Expenses (₹)",
    "Monthly Marketing Spend (₹)",
    "Growth Target (%)",
    "Select Month for Extra Financial Entry",
    "Selected Month Revenue (₹)",
    "Selected Month Expenses (₹)",
    "Selected month record not available (None)",
    "Save Profile",
    "Save and Go Dashboard",
    "Save and Continue",
    'You can edit these details later from the "Business Profile" menu in the sidebar.',
]

DASHBOARD_STRINGS = [
    "Dashboard - BizAssist AI",
    "Business Dashboard",
    "Welcome back! Here's what is happening in your business today.",
    "AI Recommendation",
    "Track low stock alerts and update pending orders to improve fulfillment speed and profitability.",
    "Total Revenue",
    "Active Orders",
    "Active Orders",
    "Low Stock Alerts",
    "Net Profit",
    "Revenue vs Expenses Trend",
    "Quick Actions",
    "Restock Required:",
    "items below threshold",
    "High Priority Orders:",
    "active orders",
    "Marketing Opportunity:",
    "VIP customers available",
    "Revenue vs Expenses Trend",
    "Quick Actions",
    "Restock Required:",
    "items below threshold",
    "High Priority Orders:",
    "active orders",
    "Marketing Opportunity:",
    "VIP customers available",
    "Restock",
    "Process",
    "Campaign",
    "Revenue",
    "Expenses",
]

INVENTORY_STRINGS = [
    "Inventory - BizAssist AI",
    "Inventory Management",
    "Track products, stock, and restocking workflow.",
    "Total Products",
    "Low Stock Alerts",
    "Inventory Value",
    "Inventory Value",
    "Add Product",
    "Add Product",
    "Product Name",
    "SKU (e.g. PR-101 or NONE)",
    "Category (select or type new)",
    "Accessories",
    "Electronics",
    "Home",
    "Fashion",
    "Health",
    "Grocery",
    "Stock",
    "Reorder Level",
    "Price (₹)",
    "Save Product",
    "Search product or SKU",
    "All Categories",
    "Filter",
    "Reset",
    "Product Inventory",
    "Product",
    "SKU",
    "Category",
    "Status",
    "Last Restocked",
    "Last Qty",
    "Actions",
    "Low Stock",
    "Well Stocked",
    "Delete this product?",
    "Delete",
]

ORDERS_STRINGS = [
    "Orders - BizAssist AI",
    "Order Management",
    "Track all incoming orders and update fulfillment status.",
    "Add New Order",
    "Customer Name",
    "Items Count",
    "Total Amount (₹)",
    "Customer Name",
    "Items Count",
    "Total Amount (₹)",
    "Create Order",
    "Search by order ID or customer",
    "All Statuses",
    "Filter",
    "Reset",
    "Recent Orders",
    "Update",
    "Save",
    "Pending",
    "Processing",
    "Shipped",
    "Delivered",
    "Order ID",
    "Customer",
    "Items",
    "Total",
    "Priority",
    "Date",
    "Delete this order?",
    "Low",
    "Medium",
    "High",
]

CUSTOMERS_STRINGS = [
    "Customers - BizAssist AI",
    "Customer Management",
    "Capture customer details to power segmentation and insights.",
    "Total Customers",
    "VIP Customers",
    "Avg Customer Value",
    "Revenue Impact",
    "Add Customer",
    "Phone",
    "VIP",
    "Regular",
    "New",
    "At Risk",
    "Category",
    "Total Orders",
    "Total Spent (₹)",
    "Add Amount (₹)",
    "Save Customer",
    "Customer List",
    "Contact",
    "Segment",
    "Last Purchase",
    "Delete this customer?",
]

FINANCE_STRINGS = [
    "Finance - BizAssist AI",
    "Finance Management",
    "Track expenses, monitor profit, and forecast future cash flow.",
    "AI Financial Insight",
    "Revenue forecast for next month is",
    "with better margin if non-essential expenses are optimized.",
    "Monthly Revenue",
    "Total Expenses",
    "Forecasted Revenue",
    "Add Expense",
    "Category",
    "Description",
    "Amount (₹)",
    "Save Expense",
    "Expense Records",
    "Edit fields and click",
    "Save row",
    "to update, or",
    "to remove a record.",
    "Expense Breakdown",
    "Next Month Forecast",
    "Expected Revenue:",
    "Expected Expenses:",
    "Delete this expense?",
]

MARKETING_STRINGS = [
    "Marketing - BizAssist AI",
    "Marketing Intelligence",
    "Create campaigns and launch them based on customer segments.",
    "Add Campaign",
    "Campaign Title",
    "Target Segment (VIP, New, At Risk)",
    "Target Customers",
    "Expected ROI %",
    "Campaign Description",
    "Save Campaign",
    "AI Recommended Campaigns",
    "Segment:",
    "Customers:",
    "ROI:",
    "Ready",
    "Draft",
    "Launched",
    "Launch Campaign",
    "Customer Segment Distribution",
    "Category Revenue Potential",
    "Inventory Value",
]

ASSISTANT_STRINGS = [
    "AI Assistant - BizAssist AI",
    "Chat Assistant",
    "Ask in any supported language. Replies follow the Reply Language you choose below.",
    "Replies use the configured NVIDIA NIM Gemma API key.",
    "Built-in questions (tap to fill, then Send)",
    "Record voice",
    "Type instead",
    "Reset chat",
    "Clear all chat messages?",
    "You",
    "AI Assistant",
    "Ask about inventory, orders, finance, growth strategy...",
    "Send",
    "Record voice",
    "Type instead",
    "Record your voice, then tap Send to continue.",
    "Clear all chat messages?",
    "Reset chat",
    "Reply Language",
    "UI",
    "Replies",
    "Business Context Used by AI",
    "Low Stock",
    "Voice and AI status updates appear here.",
    "Gemma is thinking...",
    "Speaking response...",
    "Ready for your next question.",
    "No voice content detected. Please try again.",
    "Gemma responded. You can review or edit before sending.",
    "Voice request failed. Please type your question instead.",
    "Use localhost or HTTPS for voice input.",
    "Listening... speak now.",
    "Heard:",
    "Voice recognition error:",
    "Try again.",
    "Speech recognition is unavailable. Using microphone upload instead.",
    "Recording voice... speak now for up to 8 seconds.",
    "Sending recorded audio to Gemma...",
    "Gemma replied. You can review or edit before sending.",
    "Voice recording could not be processed. Please type your message instead.",
    "Microphone permission was blocked:",
    "Please allow microphone access and try again.",
    "Microphone access is not available in this browser.",
    "Type your message in the box above.",
    "Revenue",
    "Net Profit",
    "VIP Customers",
] + [
    "What is BizAssist AI?",
    "How do I track inventory?",
    "How do I add a new product?",
    "What is net profit?",
    "How do I view my orders?",
    "How do I add a customer?",
    "What are low stock alerts?",
    "How do I update my business profile?",
    "How do I create a marketing campaign?",
    "How do I publish a discount for customers?",
    "Where can I see local offers as a shopper?",
    "How do I record an expense?",
    "What is ROI?",
    "How do I delete a discount?",
    "What segments can I target?",
    "How does the dashboard work?",
    "What financial reports are available?",
    "How do I launch a campaign?",
    "What is monthly revenue?",
    "Is my data secure?",
    "Can I use this on mobile?",
    "What currency is displayed?",
    "How do I clear the AI chat history?",
    "What is the AI assistant?",
    "How do I improve profit?",
    "What is a VIP customer?",
    "How do discounts sync to personal accounts?",
    "What does normalized location mean?",
    "How do I see the top offers in my area?",
    "Why don't I see any offers?",
]

PERSONAL_SIGNUP_STRINGS = [
    "Create a personal account",
    "A few details are enough. Your location is used to match offers from shops in the same area.",
    "Your name",
    "Full name",
    "Phone (optional)",
    "Phone number",
    "Your location (city, area, or neighbourhood)",
    "e.g. Indiranagar, Bengaluru",
    "Continue to local offers",
    "Back",
]

PERSONAL_PROFILE_STRINGS = [
    "My account",
    "Update your details. Changing location updates which shop offers you see (use the same wording as the shop for best matches).",
    "Name",
    "Location",
    "City / area",
    "Save",
]

SETTINGS_STRINGS = [
    "Settings",
    "NVIDIA NIM API Key Setup",
    "Step 1:",
    "Open the",
    "file in your project root folder",
    "Step 2:",
    "Go to",
    "and log in",
    "Step 3:",
    "Find the",
    "model and click \"Get API Key\"",
    "Step 4:",
    "Copy the API key and paste it in the",
    "file:",
    "Step 5:",
    "Restart the application",
    "Current API Key Status",
    "API Key Loaded",
    "Your NVIDIA NIM API key is configured. Model:",
    "Test Connection",
    "API Key Not Found",
    "Please follow the setup steps above to configure your API key in the",
    ".env",
    "Testing NVIDIA NIM connection...",
    "Connected",
    "Network error:",
]

STATUS_STRINGS = [
    "Well Stocked",
    "Low Stock",
    "Pending",
    "Processing",
    "Shipped",
    "Delivered",
    "Ready",
    "Draft",
    "Launched",
    "VIP",
    "Regular",
    "New",
    "At Risk",
    "High",
    "Medium",
    "Low",
]


def all_ui_strings():
    """Return deduplicated list of every UI string to pre-warm."""
    combined = (
        COMMON_STRINGS
        + LANGUAGE_SELECT_STRINGS
        + LOGIN_STRINGS
        + DASHBOARD_STRINGS
        + INVENTORY_STRINGS
        + ORDERS_STRINGS
        + CUSTOMERS_STRINGS
        + FINANCE_STRINGS
        + MARKETING_STRINGS
        + ASSISTANT_STRINGS
        + PERSONAL_SIGNUP_STRINGS
        + PERSONAL_PROFILE_STRINGS
        + SETTINGS_STRINGS
        + STATUS_STRINGS
    )
    seen = set()
    result = []
    for text in combined:
        text = str(text).strip()
        if text and text not in seen:
            seen.add(text)
            result.append(text)
    return result
